### ISSUE TITLE
Session.php error in function execute() line 467

### ISSUE THREAD

**Issue by CJMCT89** [instaclick/php-webdriver#94] opened 2019-08-13 18:20 UTC
The line is currently: $result = $this->curl('POST', '/execute', func_get_arg(1));

Which causes: Warning: func_get_arg():  Argument 1 not passed to function in C:\Projects\webs-integration-tests\vendor\instaclick\php-webdriver\lib\WebDriver\Session.php line 467

The fix is: $this->curl('POST', '/execute', func_get_arg(0));

**Comment by robocoder** [comment] 2019-08-13 18:54
Duplicate of #89

**Closed by robocoder** 2019-08-13 18:54 UTC
