### ISSUE TITLE
NoSuchElement exception for xpath //html in behat project with Selenium and geckodriver (Firefox)

### ISSUE THREAD

**Issue by jonketo** [instaclick/php-webdriver#104] opened 2020-01-23 17:32 UTC
Very similar to https://github.com/instaclick/php-webdriver/issues/98, but with Firefox and not chrome.

- chromedriver_78.0.3904.10
- geckodriver-v0.26.0
- selenium-server-standalone-3.141.59

Marionette appears to have 2 keys now which Container.php webDriverElement() is not considering. This stackoverflow answer shows them.
https://stackoverflow.com/questions/59070019/selenium-common-exceptions-nosuchelementexception-message-web-element-referenc/59073100#59073100

I also included an synopsis here https://github.com/mozilla/geckodriver/issues/1548#issuecomment-577776292

If this is the correct fix I can make a PR.

**Comment by robocoder** [comment] 2020-01-23 18:08
This is a duplicate of #98.

The likely reason why you aren't seeing the fix is because you aren't pulling in the latest version of this repo.

**Closed** 2020-01-23 18:09 UTC

**Comment by jonketo** [comment] 2020-01-23 18:26
Fixed in 1.4.5? or 2.0 RCs?

**Comment by robocoder** [comment] 2020-01-23 19:53
It was backported to the 1.x branch, in the 1.4.7 tag.
